# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kvs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tkvs.proto\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x05\"C\n\x11SetRequestMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x12\n\npropagated\x18\x03 \x01(\x08\"\x16\n\x05\x45mpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\t2Y\n\rKeyValueStore\x12\x1c\n\nGetrequest\x12\x04.Key\x1a\x06.Value\"\x00\x12*\n\nSetrequest\x12\x12.SetRequestMessage\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEY']._serialized_start=13
  _globals['_KEY']._serialized_end=31
  _globals['_VALUE']._serialized_start=33
  _globals['_VALUE']._serialized_end=55
  _globals['_SETREQUESTMESSAGE']._serialized_start=57
  _globals['_SETREQUESTMESSAGE']._serialized_end=124
  _globals['_EMPTY']._serialized_start=126
  _globals['_EMPTY']._serialized_end=148
  _globals['_KEYVALUESTORE']._serialized_start=150
  _globals['_KEYVALUESTORE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
